<?php
	// Project:    Web Reference Database (refbase) <http://www.refbase.net>
	// Copyright:  Matthias Steffens <mailto:refbase@extracts.de> and the function's
	//             original author(s).
	//
	//             This code is distributed in the hope that it will be useful,
	//             but WITHOUT ANY WARRANTY.  Please see the GNU General Public
	//             License for more details.
	//
	// File:       ./includes/export.inc.php
	// Created:    09-May-06, 15:34
	// Modified:   31-May-06, 01:50

	// This file contains functions
	// that are used when exporting
	// records from the database.

	include 'includes/transtab_refbase_bibtex.inc.php'; // include refbase markup -> BibTeX search & replace patterns

	// --------------------------------------------------------------------

	// This function takes a BibTeX file (as generated by bibutils) and
	// converts any contained refbase markup into proper LaTeX/BibTeX markup:
	function standardizeBibtexOutput($bibtexSourceText)
	{
		// The array '$transtab_refbase_bibtex' contains search & replace patterns for conversion from refbase markup to LaTeX/BibTeX markup & entities.
		// Converts refbase fontshape markup (italic, bold) into LaTeX commands of the 'textcomp' package, super- and subscript as well as greek
		// symbols get converted into the respective commands in math mode. You may need to adopt the LaTeX markup to suit your individual needs.
		global $transtab_refbase_bibtex; // defined in 'transtab_refbase_bibtex.inc.php'

		// Perform search & replace actions on the given BibTeX text:
		$bibtexSourceText = searchReplaceText($transtab_refbase_bibtex, $bibtexSourceText, true); // function 'searchReplaceText()' is defined in 'include.inc.php'

		return $bibtexSourceText;
	}

	// --------------------------------------------------------------------
?>
