<?
/*
IPOE literature database header:
*/
?>
<?
	function displayheader()
	{
		echo "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"10\" width=\"95%\" summary=\"This holds the title logo and info\">"
			. "\n<tr>"
			. "\n\t<td valign=\"middle\" rowspan=\"2\" align=\"left\" width=\"170\"><a href=\"http://www.uni-kiel.de/ipoe/\"><img src=\"img/logo.gif\" border=\"0\" alt=\"IP&Ouml; Logo\" width=\"143\" height=\"107\"></a></td>"
			. "\n\t<td><br><h2>IP&Ouml; Literature Database</h2></td>" // the <br> tag works around a display glitch in OmniWeb
			. "\n</tr>";
	}
?>
