<?
/*
IPOE literature database header:
*/
?>
<?
	function displayheader()
	{
		echo "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"10\" width=\"80%\" summary=\"This holds the title logo and info\">"
			. "\n<tr>"
			. "\n\t<td valign=\"top\" align=\"left\" width=\"170\"><a href=\"http://www.uni-kiel.de/ipoe/\"><img src=\"img/logo.gif\" border=\"0\" alt=\"IP&Ouml; Logo\" width=\"143\" height=\"107\"></a></td>"
			. "\n\t<td colspan=\"2\"><h1>IP&Ouml; Literature Database</h1></td>"
			. "\n</tr>";
	}
?>
